# Generated by Django 4.1.7 on 2023-02-27 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emp_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Derpartment',
            new_name='Department',
        ),
    ]
